<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PortForwardingService</RootNamespace>
    <AssemblyName>PortForwardingService</AssemblyName>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>pifmgr_30.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Logging\NLog.config" Link="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ini-parser" Version="2.5.2" />
    <PackageReference Include="KoKo" Version="2.4.0-beta.1" />
    <PackageReference Include="NLog" Version="6.1.4" />
    <PackageReference Include="Plugins" Version="0.0.0-beta.8" />
    <PackageReference Include="PortForwardingService.Abstractions" Version="0.0.1" />
    <PackageReference Include="qBittorrentApiClient" Version="0.0.5" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="Unfucked" Version="0.0.1-beta.49" />
    <PackageReference Include="WindowsFirewallHelper" Version="2.2.0.86" />
  </ItemGroup>

</Project>